### ISSUE TITLE
did not recognize object of type "PropertyDefinition"

### ISSUE THREAD

**Issue by nanliu666** [recursive-beast/rollup-plugin-external-assets#1]
![image](https://github.com/recursive-beast/rollup-plugin-external-assets/assets/30199403/a519d827-f66e-41eb-9408-16c2e2631703)
 ERROR  [external-assets] did not recognize object of type "PropertyDefinition"                                                                         17:06:00

 ERROR  error during build:                                                                                                                             17:06:00
Error: did not recognize object of type "PropertyDefinition"
    at Object.getFieldNames (E:\company-code\arrow\node_modules\ast-types\lib\types.js:660:19)
    at visitChildren (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:184:36)
    at Visitor.PVp.visitWithoutReset (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:166:20)
    at NodePath.each (E:\company-code\arrow\node_modules\ast-types\lib\path.js:87:26)
    at visitChildren (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:178:18)
    at Visitor.PVp.visitWithoutReset (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:166:20)
    at visitChildren (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:203:25)
    at Visitor.PVp.visitWithoutReset (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:166:20)
    at visitChildren (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:203:25)
    at Visitor.PVp.visitWithoutReset (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:166:20)
    at NodePath.each (E:\company-code\arrow\node_modules\ast-types\lib\path.js:87:26)
    at visitChildren (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:178:18)
    at Visitor.PVp.visitWithoutReset (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:166:20)
    at visitChildren (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:203:25)
    at Visitor.PVp.visitWithoutReset (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:166:20)
    at visitChildren (E:\company-code\arrow\node_modules\ast-types\lib\path-visitor.js:203:25)

**Comment by recursive-beast** [comment]
Hi, sorry for the late reply. Can you provide a minimal reproducible example please?
